from importlib.metadata import version, PackageNotFoundError

__package_name__ = "reflexio-client"

try:
    __version__ = version(__package_name__)
except PackageNotFoundError:
    # Package is not installed (e.g., running from source without installing)
    __version__ = "0.0.0-dev"


from .client import ReflexioClient
from reflexio_commons.api_schema.service_schemas import (
    UserActionType,
    ProfileTimeToLive,
    InteractionData,
    Interaction,
    UserProfile,
    PublishUserInteractionRequest,
    PublishUserInteractionResponse,
    DeleteUserProfileRequest,
    DeleteUserProfileResponse,
    DeleteUserInteractionRequest,
    DeleteUserInteractionResponse,
    RawFeedback,
    BlockingIssue,
    BlockingIssueKind,
    AddRawFeedbackRequest,
    AddRawFeedbackResponse,
    RerunProfileGenerationRequest,
    RerunProfileGenerationResponse,
    RerunFeedbackGenerationRequest,
    RerunFeedbackGenerationResponse,
    Skill,
    SkillStatus,
    RunSkillGenerationRequest,
    RunSkillGenerationResponse,
    UpdateSkillStatusRequest,
    UpdateSkillStatusResponse,
    DeleteSkillRequest,
    DeleteSkillResponse,
    ExportSkillsRequest,
    ExportSkillsResponse,
    Status,
    FeedbackStatus,
    ToolUsed,
)
from reflexio_commons.api_schema.retriever_schema import (
    SearchInteractionRequest,
    SearchUserProfileRequest,
    SearchInteractionResponse,
    SearchUserProfileResponse,
    GetSkillsRequest,
    GetSkillsResponse,
    SearchSkillsRequest,
    SearchSkillsResponse,
)
from reflexio_commons.config_schema import (
    StorageConfigTest,
    StorageConfigLocal,
    StorageConfigSupabase,
    StorageConfig,
    ProfileExtractorConfig,
    FeedbackAggregatorConfig,
    AgentFeedbackConfig,
    AgentSuccessConfig,
    ToolUseConfig,
    SkillGeneratorConfig,
    Config,
)

debug = False
log = None  # Set to either 'debug' or 'info', controls console logging


__all__ = [
    "ReflexioClient",
    "UserActionType",
    "ProfileTimeToLive",
    "InteractionData",
    "Interaction",
    "UserProfile",
    "PublishUserInteractionRequest",
    "PublishUserInteractionResponse",
    "DeleteUserProfileRequest",
    "DeleteUserProfileResponse",
    "DeleteUserInteractionRequest",
    "DeleteUserInteractionResponse",
    "RawFeedback",
    "BlockingIssue",
    "BlockingIssueKind",
    "AddRawFeedbackRequest",
    "AddRawFeedbackResponse",
    "RerunProfileGenerationRequest",
    "RerunProfileGenerationResponse",
    "RerunFeedbackGenerationRequest",
    "RerunFeedbackGenerationResponse",
    "Skill",
    "SkillStatus",
    "RunSkillGenerationRequest",
    "RunSkillGenerationResponse",
    "UpdateSkillStatusRequest",
    "UpdateSkillStatusResponse",
    "DeleteSkillRequest",
    "DeleteSkillResponse",
    "ExportSkillsRequest",
    "ExportSkillsResponse",
    "GetSkillsRequest",
    "GetSkillsResponse",
    "SearchSkillsRequest",
    "SearchSkillsResponse",
    "SkillGeneratorConfig",
    "SearchInteractionRequest",
    "SearchUserProfileRequest",
    "SearchInteractionResponse",
    "SearchUserProfileResponse",
    "StorageConfigTest",
    "StorageConfigLocal",
    "StorageConfigSupabase",
    "StorageConfig",
    "ProfileExtractorConfig",
    "FeedbackAggregatorConfig",
    "AgentFeedbackConfig",
    "AgentSuccessConfig",
    "ToolUseConfig",
    "Config",
    "Status",
    "FeedbackStatus",
    "ToolUsed",
]
